### ISSUE TITLE
Importing PartDesigner .STL files into TinkerCad fails  

### ISSUE THREAD

**Issue by JDwyer009** [marian42/partdesigner#11]
![TinkerCAD import issue](https://github.com/marian42/partdesigner/assets/70182022/fda53147-58da-490c-afa7-b19041c9815d)

PartDesigner is awesome. Is there a known work around or solution for importing PartDesigner.stl files into TinkerCad?  

In the image above the decayed piece looks awesome in PartDesigner, but fails to import into TinkerCad, but is fine for other programs like OrcaSlicer and MeshMixer. But even when I modify in MeshMixer and resave, it still imports rubbish. 

Are there special settings or steps I need to do to reformat it to make it suitable for TinkerCAD?

**Comment by JDwyer009** [comment]
Having closed the issue, does that mean there is no known solution? Or there is and I need to search harder?

**Comment by marian42** [comment]
Sorry, I should have been clearer! On the weekend, I reproduced the issue and fixed the problems in the STL export that caused this. I managed to export a part and import it in TinkerCAD and it works. So I think the issue should be fixed now! If you still find problems, please post a link to an example part.

**Comment by JDwyer009** [comment]
You are a legend. Thank you for being so responsive Marian. Much appreciated.

Just tested and it worked beautifully!!

Kind regards,  James
