### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by r03ert0** [marian42/partdesigner#2]
Part designer looks really nice! I've been using it online, but wanted to give it a try offline as well. How do you compile it / install it?
Thank you !

**Comment by marian42** [comment]
You need to have typescript installed. In the project root, run `tsc`. This should run without errors and create the file `app.js`. Now you need a webserver that locally serves the files from the project directory. If you have python installed, you can call `python3 -m http.server`. It will tell you the port, for example 8000, and you can visit http://localhost:8000 in your browser.

If you work on the code, run `tsc --watch`, which will recompile everytime you change a source file.

**Comment by r03ert0** [comment]
thank you!
