### ISSUE TITLE
Some 3d modeling optimizations

### ISSUE THREAD

**Issue by pauserratgutierrez** [marian42/partdesigner#7]
**Lego beam:**
If you add more than 2 lego beams, they are rendered without any indentation. I'm attaching pictures to compare and to explain better:
Your beams:
![legodesigner beam](https://user-images.githubusercontent.com/73240206/107616354-2c374280-6c4e-11eb-8fd2-c62f2ab18900.jpg)
This are the real lego beams.
![real lego beam](https://user-images.githubusercontent.com/73240206/107616374-3a855e80-6c4e-11eb-8129-ff011ef13dbe.jpg)

**Lego axle:**
The lego axle your program creates is flat at both ends. A real lego axle isn't that flat. (This aplies too to axles fixed to beams, all axles in general)

**Comment by marian42** [comment]
Do these indentations serve a purpose besides looking nice?
It would be really difficult to add them because they would need to work with any combination of blocks users can place. The 1x4 beam is one of the simplest examples.

**Comment by pauserratgutierrez** [comment]
> Do these indentations serve a purpose besides looking nice?
> It would be really difficult to add them because they would need to work with any combination of blocks users can place. The 1x4 beam is one of the simplest examples.

It will help us print faster each piece to save time but also will able us to save plastic. And it will be somehow more realistic. It's only an idea :)

**Comment by marian42** [comment]
It's a good idea, but unfortunaley not feasible due to the current approach to generating meshes. If I ever rewrite this app using CSG, I will add this feature.
